#!/usr/bin/python3
# Author Stephen Kennedy
import os

myPython = "myPython.d"
user_path = os.getenv("HOME")
final_path = ("%s/%s" % (user_path, myPython))
vim_path = ('.vimrc')
reset = "reset_master.py"
setup = ("update.py", "initSetup.py")

scripts = ['https://raw.githubusercontent.com/Medicup/ubuntu_init_setup/master/initSetup.py',
  'https://raw.githubusercontent.com/Medicup/fetch_update.py/master/update.py',
  'https://raw.githubusercontent.com/Medicup/ipv6_disable_debian/master/disable_ipv6.py',
  'https://raw.githubusercontent.com/Medicup/wpsiteCreate.py/master/wpsiteCreate.py',
  'https://raw.githubusercontent.com/Medicup/setIp.py/master/setIp.py',
  'https://raw.githubusercontent.com/Medicup/fabfile.py/master/fabfile.py']

# ensure reset_master.py remains executable
os.system('chmod 755 %s' % (reset))

def mypython_setup():
  if not os.path.isdir('%s' % (final_path)):
    os.system('mkdir %s ' % (final_path))

def get_scripts():
  for script in scripts:
    # get individual script from Github
    os.system("curl -O %s " % (script))

    # split the url by "/" to aid in identifying file name
    url_array = script.rsplit("/")

    # count the objects in the array and subtract 1 to get the file name
    file_position = (len(url_array)-1)
    file_name = (url_array[file_position])

    # change file permission to make executable and move to the myPython.d
    os.system('chmod 755 %s' % (file_name))
    os.system("mv %s %s" % (file_name, final_path))

def update_default():
  # update packages
  for file in setup:
    os.system('%s/%s' % (final_path, file))
    
def vim_config():
  # create .vimrc file for customization
  vimrc = ('%s/%s' % (user_path, vim_path))
  f = open(vimrc, 'w')
  
  f.write('" enable syntax highlighting \n ')
  f.write('"syntax enable \n ')

  f.write('" show line numbers \n ')
  f.write('set number \n ')

  f.write('" set tabs to have 4 spaces \n ')
  f.write('set ts=2 \n ')

  f.write('" indent when moving to the next line while writing code \n ')
  f.write('set autoindent \n ')

  f.write('" expand tabs into spaces \n ')
  f.write('set expandtab \n ')

  f.write('" when using the >> or << commands, shift lines by 4 spaces \n ')
  f.write('set shiftwidth=2 \n ')

  f.write('" show a visual line under the cursor current line \n ')
  f.write('set cursorline \n ')

  f.write('" show the matching part of the pair for [] { \n ')
  f.write('" } and () \n ')
  f.write('set showmatch \n ')

  f.write('" enable all Python syntax hiGghlighting features \n ')
  f.write('let python_highlight_all = 1 \n ')

  f.write('"filetype plugin indent on  \n ')
  f.write('"set softtabstop=2  \n ')
  f.write('"set ai  \n ')
  f.write('set autoindent  \n ')
  f.write('"set smartindent \n ')
  f.write('inoremap { {<CR><CR>}<C-o>k<C-o>S  \n ')
 
os.system('chmod 755 %s' % (reset))

mypython_setup()
get_scripts()
vim_config()
update_default()
